# Only build master branch (leave other branch builds up to PRs)
branches:
  only:
    - master

language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-28

android:
  components:
    - build-tools-28.0.3
    - $ANDROID_TARGET

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

install: ./gradlew clean assemble --stacktrace

script: ./gradlew check --stacktrace
