name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Assemble
        run: ./gradlew clean assemble --stacktrace
      - name: Check
        run: ./gradlew check --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
