name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build (including JVM tests)
        run: ./gradlew clean build --stacktrace
